### ISSUE TITLE
Ssh into VPN

### ISSUE THREAD

**Issue by nnaemekaopara** [ShVerni/Raspberry-Pi-VPN-Gateway#1]
Hello there, I saw your comment on superjamie's page and was hoping I could ask for your help. I know this area is used to raise potential issues with your code but i really needed to contat you and this is the only way possible. I need help with a project I am running. I would be very grateful.

I am trying to establish an ssh connection over the vpn connection that your setup does. I am running a project to analyse threats based on locations and the only way i could do this is through a vpn connection to different regions. after installing the vpn, I opened the port 22 on my router and forwarded it to the system in order to be able to ssh into the device using its vpn public ip but the issue is, a VPN connection was created to disable such attacks.  Please will it be possible to establish an ssh connection over the vpn

**Comment by ShVerni** [comment]
Hello,

I'm afraid from what Ive read, there's no way to open a specific port, such as 22, into the VPN tunnel using PIA. You can use their client software and they will open a random port for you, but it seems that's the only option:

https://helpdesk.privateinternetaccess.com/hc/en-us/articles/219460187-How-do-I-enable-port-forwarding-on-my-VPN

Best of luck!
