### ISSUE TITLE
Silence prompts during iptables-persistent install

### ISSUE THREAD

**Issue by musicin3d** [ShVerni/Raspberry-Pi-VPN-Gateway#3]
The prompts for saving the current iptables configuration can be silenced. This would require less babysitting. :)

Check out https://gist.github.com/alonisser/a2c19f5362c2091ac1e7

Basically, adding the following before `apt-get install`...

```
echo iptables-persistent iptables-persistent/autosave_v4 boolean false | sudo debconf-set-selections
echo iptables-persistent iptables-persistent/autosave_v4 boolean false | sudo debconf-set-selections
```

Note: This is different from the linked gist. I've changed it to `false` since you're going to save later in the installation.

I would fork this and try it myself, but I don't have a spare PI right now. :)

**Comment by ShVerni** [comment]
Awesome, thanks for the great tip! The commands seem to run fine on a Raspberry Pi, though I didn't test installing iptables-persistent as I didn't want to risk breaking my current setup. Still, I added the suggested lines to the script since it will probably work without issue.
