### ISSUE TITLE
option to work the other way around?

### ISSUE THREAD

**Issue by spants** [ShVerni/Raspberry-Pi-VPN-Gateway#4]
Great job on the script!.

I'd like an option to work differently:
1) redirect any requests to a (specific) port number (eg any ip but has port 1234) to tun0 (vpn)
2) allow all other requests to go to eth0 (normal gateway)
3) (optional dns requests to go to vpn)

Would this be difficult to do?

**Comment by ShVerni** [comment]
Thanks!

It should be very possible. I haven't tested this, but here's what should (maybe) work. First, you definitely want to make sure you don't use the kill-switch. If you don't want DNS to go over the VPN you can comment out the following line from the script (currently line 207):
```
iptables -t nat -A PREROUTING -i eth0 -p tcp -m tcp --dport 53 -j DNAT --to-destination 127.0.0.1
```
If you do want DNS over the VPN, leave it in place and add these two iptables rules with the following commands (these lines are probably overkill and not needed, but they won't hurt):
```
sudo iptables -A OUTPUT -o eth0 -p udp -m udp --dport 53 -m comment --comment "dns" -j ACCEPT
sudo iptables -A OUTPUT -o eth0 -p tcp -m tcp --dport 53 -m comment --comment "dns" -j ACCEPT
```
If you want to have specific ports go over the VPN, first comment out this line from the script, which forwards all traffic over the VPN (currently line 209):
```
iptables -A FORWARD -i eth0 -o tun0 -j ACCEPT
```
Then you can use the following command to forward certain ports over the VPN:
```
sudo iptables -A FORWARD -i eth0 -o tun0 -p [protocol] --dport [port] -j ACCEPT
```
Where `[protocol]` and `[port]` are the respective protocol and port. For example:
```
sudo iptables -A FORWARD -i eth0 -o tun0 -p tcp --dport 80 -j ACCEPT
```
That should forward all HTTP traffic over the VPN. Again, I have not tested this, and am no expert in iptables, but hopefully that will work, or at least get you started.

I should note that you need to install the VPN script before entering any iptables rules, as the script will clobber any rules you had before running it.
