### ISSUE TITLE
DNS Leaks

### ISSUE THREAD

**Issue by HiDef888** [ShVerni/Raspberry-Pi-VPN-Gateway#5]
I noticed there was no 'update-resolv-conf'  up & down in the config file it generates.
I can confirm that this script doesn't use PIA dns servers and is thus leaking DNS requests unfortunately.
Perhaps including in config file something to update resolv conf?
`script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf`
could possibly fix issue

**Comment by HiDef888** [comment]
F/U
I confirmed adding the lines
script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
To the vpn.conf file is now forwarding all DNS requests through VPN and not leaking.

**Comment by ShVerni** [comment]
Thanks for the suggestion! I've updated the scripts with your additions and they seem to work great.
